//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class haber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public haber()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public string haberId { get; set; }
        public string haberBasligi { get; set; }
        public string haberİcerigi { get; set; }
        public System.DateTime haberTarihi { get; set; }
        public byte[] haberResmi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
    }
}
